import { z } from 'https://deno.land/x/zod@v3.22.4/mod.ts';

export const vendaSchema = z.object({
  identificacao_unica: z.string().optional(),
  data_contrato: z.string().optional(),
  flow_status: z.string().optional(),
  status_evento: z.string().optional(),
  status_pagamento: z.enum(['pendente', 'parcial', 'pago', 'atrasado']).default('pendente'),
  observacoes_internas: z.string().optional(),
  perdas_reais: z.number().optional(),
  pendencias_financeiras: z.string().optional(),
  check_financeiro: z.string().optional(),
  valor_total: z.number().default(0),
  valor_entrada: z.number().optional(),
  forma_pagamento_confirmada: z.string().optional(),
  forma_pagamento_selecionada: z.string().optional(),
  nome_cliente: z.string().optional(),
  telefone_cliente: z.string().optional(),
  email_cliente: z.string().email().optional().or(z.literal('')),
  cpf_cliente: z.string().optional(),
  cnpj_cliente: z.string().optional(),
  endereco_residencial: z.string().optional(),
  complemento_endereco: z.string().optional(),
  canal_origem: z.string().optional(),
  email_vendedor: z.string().email().optional().or(z.literal('')),
  nota_atendimento_vendas: z.number().min(0).max(10).optional(),
  submission_ip: z.string().optional(),
  submission_id: z.string().optional(),
  data_ultima_atualizacao: z.string().optional(),
  tags: z.string().optional(),
  subtotal: z.number().optional(),
  desconto: z.number().optional(),
  observacoes_integradas: z.string().optional(),
  valor_recebido: z.number().default(0),
  data_venda: z.string().optional(),
});

export const eventoSchema = z.object({
  identificacao_unica: z.string().optional(),
  nome: z.string().min(1),
  cliente: z.string().min(1),
  data_evento: z.string().min(1),
  tipo_evento: z.enum(['casamento', 'aniversario', 'corporativo', 'formatura', 'outro']).default('outro'),
  status: z.enum(['pendente', 'confirmado', 'realizado', 'cancelado']).default('confirmado'),
  hora_inicio: z.string().optional(),
  endereco_evento: z.string().optional(),
  endereco_igual_residencial: z.boolean().optional(),
  tipo_local: z.string().optional(),
  qtd_criancas_prevista: z.number().optional(),
  faixa_etaria: z.string().optional(),
  tema: z.string().optional(),
  nome_aniversariante: z.string().optional(),
  idade_aniversariante: z.number().optional(),
  horas_contratadas: z.number().optional(),
  servicos_contratados: z.string().optional(),
  qtd_recreadores_contratados: z.number().optional(),
  pacote_visual: z.string().optional(),
  permite_alimentacao_recreador: z.boolean().optional(),
  atividades_adicionais: z.string().optional(),
  orientacoes_especiais: z.string().optional(),
  informacoes_rotina_evento: z.string().optional(),
  observacoes: z.string().optional(),
  observacoes_cliente: z.string().optional(),
  necessidades_especiais: z.string().optional(),
  alertas_seguranca: z.string().optional(),
  duracao_prevista: z.number().optional(),
  atividades_personalizadas: z.string().optional(),
  submission_ip: z.string().optional(),
  submission_id: z.string().optional(),
  data_ultima_atualizacao: z.string().optional(),
});

export const profissionalSchema = z.object({
  identificacao_registro: z.string().optional(),
  nome: z.string().min(1),
  apelido: z.string().optional(),
  cpf: z.string().optional(),
  data_nascimento: z.string().optional(),
  telefone: z.string().optional(),
  email: z.string().email().optional().or(z.literal('')),
  funcao: z.string().default('Recreador'),
  endereco: z.string().optional(),
  chave_pix: z.string().optional(),
  chave_pix_confirmada: z.string().optional(),
  meio_transporte: z.string().optional(),
  tempo_experiencia: z.string().optional(),
  faixa_etaria_experiencia: z.string().optional(),
  formacao_academica: z.string().optional(),
  cursos_especializacoes: z.string().optional(),
  motivacao: z.string().optional(),
  case_sucesso: z.string().optional(),
  referencias_profissionais: z.string().optional(),
  habilidades: z.record(z.string()).optional(),
  uniforme_calca: z.string().optional(),
  uniforme_camiseta: z.string().optional(),
  uniforme_macacao: z.string().optional(),
  possui_cnpj: z.string().optional(),
  frequencia_desejada: z.string().optional(),
  interesse_pacotes_mensais: z.string().optional(),
  interesse_mais_eventos: z.string().optional(),
  interesses_curto_longo_prazo: z.string().optional(),
  submission_id: z.string().optional(),
  submission_ip: z.string().optional(),
  data_cadastro: z.string().optional(),
  data_ultima_atualizacao: z.string().optional(),
  flow_status: z.string().optional(),
  ativo: z.boolean().default(true),
});

export const satisfacaoSchema = z.object({
  tipo: z.string().optional(),
  identificacao_unica: z.string().optional(),
  evento_id: z.string().uuid().optional(),
  data_avaliacao: z.string().min(1),
  nota: z.number().min(0).max(10),
  cpf_avaliador: z.string().optional(),
  nome_avaliador: z.string().optional(),
  nome_cliente: z.string().optional(),
  nps_score: z.number().min(0).max(10).optional(),
  nota_qualidade_recreacao: z.number().min(0).max(10).optional(),
  nota_profissionais: z.number().min(0).max(10).optional(),
  recontrataria: z.string().optional(),
  comentario: z.string().optional(),
  comentario_aberto: z.string().optional(),
  nota_informacoes_previas: z.number().min(0).max(10).optional(),
  nota_adequacao_atividades: z.number().min(0).max(10).optional(),
  nota_engajamento_criancas: z.number().min(0).max(10).optional(),
  nota_feedback_criancas: z.number().min(0).max(10).optional(),
  nota_materiais: z.number().min(0).max(10).optional(),
  nota_suporte_casting: z.number().min(0).max(10).optional(),
  nota_cumprimento_cronograma: z.number().min(0).max(10).optional(),
  nota_entrega_materiais: z.number().min(0).max(10).optional(),
  nota_completude_materiais: z.number().min(0).max(10).optional(),
  obs_casting_logistica_materiais: z.string().optional(),
  escopo_projeto: z.string().optional(),
  nota_reacao_pais: z.number().min(0).max(10).optional(),
  feedback_contratante: z.string().optional(),
  nota_geral: z.number().min(0).max(10).optional(),
  obs_equipe_evento: z.string().optional(),
  submission_ip: z.string().optional(),
  submission_id: z.string().optional(),
  data_ultima_atualizacao: z.string().optional(),
  tags: z.string().optional(),
  data_resposta: z.string().optional(),
});

export const reclamacaoSchema = z.object({
  data_abertura: z.string().optional(),
  responsavel_abertura: z.string().optional(),
  nome_cliente: z.string().optional(),
  telefone_cliente: z.string().optional(),
  descricao: z.string().optional(),
  identificacao_unica: z.string().optional(),
  evento_id: z.string().uuid().optional(),
  anexos: z.string().optional(),
  submission_id: z.string().optional(),
});

export const controleConferenciaSchema = z.object({
  data_conferencia: z.string().optional(),
  nome_avaliador: z.string().optional(),
  anexos: z.string().optional(),
  marcador: z.string().optional(),
  evento_id: z.string().uuid().optional(),
  itens_consumidos_totalmente: z.string().optional(),
  checklist_preenchido: z.string().optional(),
  uniforme_usado: z.string().optional(),
  usou_pintura_facial: z.string().optional(),
  usou_baloes: z.string().optional(),
  houve_divergencia: z.string().optional(),
  caixa_organizada: z.string().optional(),
  id_montagem: z.string().optional(),
  itens_ausentes: z.string().optional(),
  comentarios: z.string().optional(),
  submission_id: z.string().optional(),
});
